name: Sync to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Private Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Public Repo
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git remote add public https://preetamslot:${{ secrets.REPO_TOKEN }}@github.com/unfolding-io/Astrogency.git
          git push -u public master --force
