name: Sync to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Private Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global gc.auto 0

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fetch Remote Updates
        run: git fetch --all

      - name: Rebuild Git Index
        run: |
          git reset --hard
          git gc --aggressive --prune=now

      - name: Pull latest changes
        run: git pull origin master

      - name: Push to Public Repo
        run: |
          git remote add public git@github.com:unfolding-io/Astrogency.git
          git push -u public master --force
