name: Sync to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Private Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fetch from Public Repo
        run: |
          git remote add public git@github.com:unfolding-io/Astrogency.git
          git fetch public

      - name: Merge Public Repo Changes
        run: |
          git merge public/master --allow-unrelated-histories

      - name: Push to Public Repo
        run: |
          git push -u public master --force
